In [18]:
import numpy as np

a = np.array([1,2,3]) # 벡터
b = np.array([[1,2,3],[4,5,6],[5,6,7]]) # 3x3 행렬
c = np.array([[1,2],[2,3]]) # 2x2 행렬

print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [5 6 7]]
[[1 2]
 [2 3]]


In [24]:
# ndarray라는 형식의 변수
print(a.ndim) # dimension = 차원, 1 = 벡터, 2 = 행렬
print(b.ndim)

print(a.shape) # 행
print(b.shape) # 행, 열
print(c.shape)

print(a.size) # 전체 스칼라의 개수
print(b.size)
print(c.size)

1
2
(3,)
(3, 3)
(2, 2)
3
9
4


In [7]:
x = np.zeros((3,2)) # 0으로 가득찬, 3x2 행렬
y = np.ones((3,4)) # 1로 가득찬, 3x4 행렬
z = np.full((2,3), 5) # 5로 가득찬, 2x3 행렬

print(x)
print(y)
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]]


In [17]:
# np.arange(시작하는값, 끝나는값(디폴트 = 포함x), 증가량(디폴트 = 1))
x = np.arange(0, 10, 3)

# np.linspace(시작하는값, 끝나는값(디폴트 = 포함o), 개수)
y = np.linspace(0, 10, 5)

print(x)
print(y)

[0 3 6 9]
[0. 2. 4. 6. 8.]


In [29]:
a = np.arange(0,10)
print(a)

b = a.reshape(2,5) # 순서가 중요함!
print(b)

[0 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 10 into shape (3,3)

In [44]:
# b[행,열]
print(b)
print(b[0,:]) # b의 0행(=첫번째행), 열은 전부다
print(b[:,0]) # b의 1열(=두번째열), 행은 전부다

print(b[3,:]) # b의 3행(=네번째행), 열 전부다

[[  0   1]
 [  2   3]
 [  4 100]
 [  6   7]
 [  8   9]]
[0 1]
[0 2 4 6 8]
[6 7]


In [60]:
c = np.arange(0,12)
c = c.reshape(4,3)
print(c)

# : = 맨처음부터, 맨끝까지(포함o)
# (시작하는 지점, 이상):(끝지점, 포함x, 미만)
# 0부터 시작, 첫번째행 = 0, 첫번째열 = 0

# print(c[0,:]) # 첫번째 행, 열은 전부다
# print(c[0,1:]) # c[첫번째행, 두번째열부터~끝까지]
# print(c[2:,1]) # c[세번째행부터~끝행까지, 두번째열]

# print(c[:2,1]) # c[첫번째행부터~세번째행까지(끝 포함x), 두번째열]
# print(c[1:3,2:]) # 두번째행부터~네번째행까지(끝 포함x), 세번째열부터~마지막열까지

print(c[-1,-1]) # -1 = 뒤에서 첫번째 = 맨끝, -2 = 뒤에서 두번째
print(c[-2,-2])
print(c[-3,-2])
print(c[-4,-3])

print(c[1:-1,1:-1]) # 두번째행부터~마지막행까지(포함x), 두번째열부터~마지막열까지(포함x)
print(c[0:-2,2]) # 첫번째행부터~뒤에서두번째행까지(포함x) = 0행~2행(포함x) = 0행~1행, 세번째열

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]
[2 5]
